**Step 1: Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string

**Step 2: Load the dataset**

In [5]:
full_df = pd.read_csv('/content/1429_1.csv', nrows=3000)
df = full_df[["reviews.text","reviews.title"]]
df[["reviews.text","reviews.title"]] = df[["reviews.text","reviews.title"]].astype(str)
full_df.head()

<ipython-input-5-6afedb6f0cd7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["reviews.text","reviews.title"]] = df[["reviews.text","reviews.title"]].astype(str)

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [21]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

**Tokenization:**

In [22]:
import re

def tokenize(text):
    tokens = re.split('\W+', text)
    return tokens

df['reviews.title_tokenized'] = df['reviews.title'].apply(lambda x: tokenize(x.lower()))

df['reviews.text_tokenized'] = df['reviews.text'].apply(lambda x: tokenize(x.lower()))

df.head()

<ipython-input-22-04fb8c021839>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.title_tokenized'] = df['reviews.title'].apply(lambda x: tokenize(x.lower()))
<ipython-input-22-04fb8c021839>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviews.text_tokenized'] = df['reviews.text'].apply(lambda x: tokenize(x.lower()))

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,review.text_lemmatized,review.title_lemmatized,reviews.title_tokenized,reviews.text_tokenized
0,This product so far has not disappointed. My c...,Kindle,thi product so far ha not disappointed. my chi...,kindl,This product so far ha not disappointed. My ch...,Kindle,[kindle],"[this, product, so, far, has, not, disappointe..."
1,great for beginner or experienced person. Boug...,very fast,great for beginn or experienc person. bought a...,veri fast,great for beginner or experienced person. Boug...,very fast,"[very, fast]","[great, for, beginner, or, experienced, person..."
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,"inexpens tablet for him to use and learn on, s...",beginn tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,"[beginner, tablet, for, our, 9, year, old, son, ]","[inexpensive, tablet, for, him, to, use, and, ..."
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,i'v had my fire hd 8 two week now and i love i...,good!!!,I've had my Fire HD 8 two week now and I love ...,Good!!!,"[good, ]","[i, ve, had, my, fire, hd, 8, two, weeks, now,..."
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,i bought thi for my grand daughter when she co...,fantast tablet for kid,I bought this for my grand daughter when she c...,Fantastic Tablet for kid,"[fantastic, tablet, for, kids]","[i, bought, this, for, my, grand, daughter, wh..."

**Lower Casing:**

In [23]:
# drop the new column created in last cell
df.drop(["reviews.text_tokenized"], axis=1, inplace=True)
df.drop(["reviews.title_tokenized"], axis=1, inplace=True)
df["reviews.text_lower"] = df["reviews.text"].str.lower()
df["reviews.title_lower"] = df["reviews.title"].str.lower()
df.head()

<ipython-input-23-ccc1edd5042d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.text_tokenized"], axis=1, inplace=True)
<ipython-input-23-ccc1edd5042d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.title_tokenized"], axis=1, inplace=True)
<ipython-input-23-ccc1edd5042d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_lower"] = df["reviews.text"].str.lower()
<ipython-input-23-ccc1edd5042d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_lower"] = df["reviews.title"].str.lower()

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,review.text_lemmatized,review.title_lemmatized,reviews.text_lower,reviews.title_lower
0,This product so far has not disappointed. My c...,Kindle,thi product so far ha not disappointed. my chi...,kindl,This product so far ha not disappointed. My ch...,Kindle,this product so far has not disappointed. my c...,kindle
1,great for beginner or experienced person. Boug...,very fast,great for beginn or experienc person. bought a...,veri fast,great for beginner or experienced person. Boug...,very fast,great for beginner or experienced person. boug...,very fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,"inexpens tablet for him to use and learn on, s...",beginn tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,inexpensive tablet for him to use and learn on...,beginner tablet for our 9 year old son.
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,i'v had my fire hd 8 two week now and i love i...,good!!!,I've had my Fire HD 8 two week now and I love ...,Good!!!,i've had my fire hd 8 two weeks now and i love...,good!!!
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,i bought thi for my grand daughter when she co...,fantast tablet for kid,I bought this for my grand daughter when she c...,Fantastic Tablet for kid,i bought this for my grand daughter when she c...,fantastic tablet for kids

**Removal of Punctuations:**

In [7]:
#drop the new column created in last cell
df.drop(["reviews.text_lower"], axis=1, inplace=True)
df.drop(["reviews.title_lower"], axis=1, inplace=True)

PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["reviews.text_wo_punct"] = df["reviews.text"].apply(lambda text: remove_punctuation(text))
df["reviews.title_wo_punct"] = df["reviews.title"].apply(lambda text: remove_punctuation(text))
df.head()

<ipython-input-7-33a12da28f45>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.text_lower"], axis=1, inplace=True)
<ipython-input-7-33a12da28f45>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.title_lower"], axis=1, inplace=True)
<ipython-input-7-33a12da28f45>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_wo_punct"] = df["reviews.text"].apply(lambda text: remove_punctuation(text))
<ipython-input-7-33a12da28f45>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_wo_punct"] = df["reviews.title"].apply(lambda text: remove_punctuation(text))

,reviews.text,reviews.title,reviews.text_wo_punct,reviews.title_wo_punct
0,This product so far has not disappointed. My c...,Kindle,This product so far has not disappointed My ch...,Kindle
1,great for beginner or experienced person. Boug...,very fast,great for beginner or experienced person Bough...,very fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,Ive had my Fire HD 8 two weeks now and I love ...,Good
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,I bought this for my grand daughter when she c...,Fantastic Tablet for kids

**Removal of stopwords:**

In [8]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [9]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [10]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df["reviews.text_wo_stop"] = df["reviews.text_wo_punct"].apply(lambda text: remove_stopwords(text))
df["reviews.title_wo_stop"] = df["reviews.title_wo_punct"].apply(lambda text: remove_stopwords(text))
df.head()

<ipython-input-10-900b1dc19b38>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_wo_stop"] = df["reviews.text_wo_punct"].apply(lambda text: remove_stopwords(text))
<ipython-input-10-900b1dc19b38>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_wo_stop"] = df["reviews.title_wo_punct"].apply(lambda text: remove_stopwords(text))

,reviews.text,reviews.title,reviews.text_wo_punct,reviews.title_wo_punct,reviews.text_wo_stop,reviews.title_wo_stop
0,This product so far has not disappointed. My c...,Kindle,This product so far has not disappointed My ch...,Kindle,This product far disappointed My children love...,Kindle
1,great for beginner or experienced person. Boug...,very fast,great for beginner or experienced person Bough...,very fast,great beginner experienced person Bought gift ...,fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son,Inexpensive tablet use learn step NABI He thri...,Beginner tablet 9 year old son
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,Ive had my Fire HD 8 two weeks now and I love ...,Good,Ive Fire HD 8 two weeks I love This tablet gre...,Good
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,I bought grand daughter comes visit I set user...,Fantastic Tablet kids

**Stemming**

In [11]:
from nltk.stem.porter import PorterStemmer

In [12]:
#Drop the two columns
df.drop(["reviews.text_wo_stop", "reviews.text_wo_punct"], axis=1, inplace=True)
df.drop(["reviews.title_wo_stop", "reviews.title_wo_punct"], axis=1, inplace=True)

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["reviews.text_stemmed"] = df["reviews.text"].apply(lambda text: stem_words(text))
df["reviews.title_stemmed"] = df["reviews.title"].apply(lambda text: stem_words(text))
df.head()

<ipython-input-12-7cc513f8cd9d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.text_wo_stop", "reviews.text_wo_punct"], axis=1, inplace=True)
<ipython-input-12-7cc513f8cd9d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["reviews.title_wo_stop", "reviews.title_wo_punct"], axis=1, inplace=True)
<ipython-input-12-7cc513f8cd9d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.text_stemmed"] = df["reviews.text"].apply(lambda text: stem_words(text))
<ipython-input-12-7cc513f8cd9d>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["reviews.title_stemmed"] = df["reviews.title"].apply(lambda text: stem_words(text))

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed
0,This product so far has not disappointed. My c...,Kindle,thi product so far ha not disappointed. my chi...,kindl
1,great for beginner or experienced person. Boug...,very fast,great for beginn or experienc person. bought a...,veri fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,"inexpens tablet for him to use and learn on, s...",beginn tablet for our 9 year old son.
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,i'v had my fire hd 8 two week now and i love i...,good!!!
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,i bought thi for my grand daughter when she co...,fantast tablet for kid

**Lemmatization**

In [14]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [15]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["review.text_lemmatized"] = df["reviews.text"].apply(lambda text: lemmatize_words(text))

df["review.title_lemmatized"] = df["reviews.title"].apply(lambda text: lemmatize_words(text))
df.head()

<ipython-input-15-b8227d6b1cf2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["review.text_lemmatized"] = df["reviews.text"].apply(lambda text: lemmatize_words(text))
<ipython-input-15-b8227d6b1cf2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["review.title_lemmatized"] = df["reviews.title"].apply(lambda text: lemmatize_words(text))

,reviews.text,reviews.title,reviews.text_stemmed,reviews.title_stemmed,review.text_lemmatized,review.title_lemmatized
0,This product so far has not disappointed. My c...,Kindle,thi product so far ha not disappointed. my chi...,kindl,This product so far ha not disappointed. My ch...,Kindle
1,great for beginner or experienced person. Boug...,very fast,great for beginn or experienc person. bought a...,veri fast,great for beginner or experienced person. Boug...,very fast
2,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,"inexpens tablet for him to use and learn on, s...",beginn tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.
3,I've had my Fire HD 8 two weeks now and I love...,Good!!!,i'v had my fire hd 8 two week now and i love i...,good!!!,I've had my Fire HD 8 two week now and I love ...,Good!!!
4,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,i bought thi for my grand daughter when she co...,fantast tablet for kid,I bought this for my grand daughter when she c...,Fantastic Tablet for kid